"""first migration

Revision ID: 331ed9f92673
Revises: 
Create Date: 2021-02-28 09:39:48.463090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '331ed9f92673'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread', sa.String(), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threads_id'), 'threads', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threads_id'), table_name='threads')
    op.drop_table('threads')
    # ### end Alembic commands ###
